### ISSUE TITLE
northern border tp issue

### ISSUE THREAD

**Issue by superon** [UpcraftLP/WorldLimiterMod#2]
took me w hime to work out that i'm supposed to set the     I:maxWorldSize= (1 block smaller than the world border edge), once done though i works superbly... apart from the northern border for whatever reason fps me to the south eastern edge of the map no matter at what point it as accessed.    might be an issue with mod compatibility, hoping not tho as for now i've got to go before posting any more...      thank you for working on this project:)   now i just need to edit my world so the tps appear seamless with the terrain.

**Comment by UpcraftLP** [comment]
Fixed in v1.0.2 for MC 1.10.2
